### ISSUE TITLE
rescale stopped working with dist objects

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/scales#102]
`rescale()` used to work with `dist` objects as exemplified [here](https://onlinelibrarystatic.wiley.com/store/10.1111/2041-210X.12735/asset/supinfo/mee312735-sup-0004-AppendixS4.R?v=1&s=7eecca9a563372b23be43debb5f1d2aafcaba168) (SI from https://doi.org/10.1111/2041-210X.12735).

It was broken by #75. 

> Error in UseMethod("rescale") : 
>  no applicable method for 'rescale' applied to an object of class "dist"

Do you explicitly want to remove support for `dist` objects or is it simply a side-effect of the changes in #75?

**Comment by zeehio** [comment]
Hi @Bisaloo, as the author of #75 I am sorry for the inconveniences. I wish I had seen your issue earlier. I have already submitted a pull request, would you like to try the patch?

```
devtools::install_github("zeehio/scales@fix_102")
```

**Comment by Bisaloo** [comment]
It's exactly the old function so I expect everything will be fine. I just tested on a random `dist` object just in case and it works fine.

Thank you for taking care of this!
