### ISSUE TITLE
Function colour_ramp() should respect transparency by default

### ISSUE THREAD

**Issue by clauswilke** [r-lib/scales#108]
The function `colour_ramp()` has the option to ramp RGBA colors instead of RGB colors. However, by default, this option is switched off, and the function removes any alpha values that may be attached to the colors it is given.

This seems to be an unusual default setting. If somebody goes to the effort of adding alpha values to colors, I would assume they want those respected. Also, this creates inconsistency between discrete and continuous color scales. Discrete scales respect alpha value, continuous ones do not.

Reproducible example: First a case using a discrete color scale.

```
library(ggplot2)

ggplot(iris, aes(Sepal.Length, fill = Species)) + 
  geom_density() +
  scale_fill_manual(values = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

<img width="661" alt="screen shot 2017-12-19 at 6 59 33 pm" src="https://user-images.githubusercontent.com/4210929/34186236-106a2ad8-e4f0-11e7-8dce-c2749d5d5895.png">

The transparency values of the colors are respected. Now the same plot using a continuous color scale:
```
ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), group = Species)) + 
  geom_density() +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

<img width="661" alt="screen shot 2017-12-19 at 6 59 45 pm" src="https://user-images.githubusercontent.com/4210929/34186246-2573d032-e4f0-11e7-9517-dc2d7e8655ce.png">

Transparency is gone.

However, if we switch the `alpha` option to `TRUE` in function `colour_ramp()`, things behave as expected:

```
# change the default setting of scales::colour_ramp:
assignInNamespace("colour_ramp", function(colors, na.color = NA, alpha = TRUE){
  if (length(colors) == 0) {
    stop("Must provide at least one color to create a color ramp")
  }
  colorMatrix <- grDevices::col2rgb(colors, alpha = alpha)
  structure(function(x) {
    scales:::doColorRamp(colorMatrix, x, alpha, ifelse(is.na(na.color), 
                                                       "", na.color))
  }, safe_palette_func = TRUE)
}, "scales")

ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), group = Species)) + 
  geom_density() +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

<img width="661" alt="screen shot 2017-12-19 at 7 00 09 pm" src="https://user-images.githubusercontent.com/4210929/34186265-45b7d3d4-e4f0-11e7-9786-8da3ff8645eb.png">

**Comment by lukasjonkers** [comment]
I am trying to use this to change the transparency of colour and fill of `geom_polygon`, but noticed that the solution above affects colour and fill differently. The difference is only small, but leads to very ugly graphs with tightly spaced polygons (e.g. maps)

```
ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), colour = as.numeric(Species), group = Species)) + 
  geom_density() +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20")) +
  scale_colour_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

![image](https://user-images.githubusercontent.com/38979118/47225218-d58f0600-d3bd-11e8-8ec8-6ef9d422beac.png)

Any clue why this might be and how to fix it?

**Comment by clauswilke** [comment]
It is not the case that color and fill are affected differently. Instead, the lines are drawn on top of the fill area and therefore those regions appear darker. We can exaggerate this effect by making the lines thicker. And we can avoid it by removing the lines altogether.

``` r
library(ggplot2)

# make line thicker to highlight the problem
ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), colour = as.numeric(Species), group = Species)) + 
  geom_density(size = 5) +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20")) +
  scale_colour_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

![](https://i.imgur.com/bZ8dupW.png)

``` r

# remove lines altogether
ggplot(iris, aes(Sepal.Length, fill = as.numeric(Species), group = Species)) + 
  geom_density(color = NA) +
  scale_fill_gradientn(colors = c("#00FF00FF", "#008000B0", "#0000FF20"))
```

![](https://i.imgur.com/re1PjVo.png)

<sup>Created on 2018-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by lukasjonkers** [comment]
I see, should have thought about that myself. That makes it hard to use transparency and get rid of the blank/white lines when plotting polygons.

![image](https://user-images.githubusercontent.com/38979118/47256842-4863b400-d486-11e8-9f0e-dff86913ca8a.png)

Because I seem to need the lines for that purpose.

Code from [here](https://www.uv.es/mimica/Rblog/polygon.html)

**Comment by clauswilke** [comment]
Yes, that's a fundamental limitation of the current R graphics architecture, and it's the reason why my gradient geoms from the ggridges package don't allow transparency.
