### ISSUE TITLE
scales::percent adds comma's

### ISSUE THREAD

**Issue by markvanderloo** [r-lib/scales#140]
Saw this pop up via twitter.

```r
> scales::percent(1e4)
[1] "1,000,000%"
```
two issues:

1. Comma separator is not documented.
2. The comma as 'big' separator is biased to the North-American convention. In European countries (including NL), we use comma as decimal separator and dot as big separator (especially for, but not limited to financial amounts). 

Would be nice to have an option like `big.mark` behaving like the same option in `base::format`.

**Comment by hadley** [comment]
Related to #79, and should be part of #77
