### ISSUE TITLE
Enhance Supporting Nonstandard Classes in train_continuous

### ISSUE THREAD

**Issue by billdenney** [r-lib/scales#166]
Could `train_continuous` also include an `if` block for the case when `existing` is `NULL` to better work with nonstandard classes??

``` r
train_continuous <- function(new, existing = NULL) {
  if (is.null(new)) return(existing)
  
  if (is.factor(new) || !typeof(new) %in% c("integer", "double")) {
    stop("Discrete value supplied to continuous scale", call. = FALSE)
  }
  if (is.null(existing)) {
    suppressWarnings(range(new, na.rm = TRUE, finite = TRUE))
  } else {
    suppressWarnings(range(existing, new, na.rm = TRUE, finite = TRUE))
  }
}
```

This issue relates to r-quantities/units#164.

When trying to use `train_continuous` with a nonstandard class, it ends up calling `range(existing, new)` (https://github.com/r-lib/scales/blob/3c17ebf8a9babd61b0e7b999aae83ee08e2f03f1/R/scale-continuous.r#L41).  With classes beyond base classes (in the case listed above, the 'units' class), this causes the class to be lost and yields issues down the line when using classes that cannot be directly compared.

**Comment by hadley** [comment]
Looks good. Want to do a PR?

**Comment by billdenney** [comment]
PR is coming shortly.  FYI, I looked at `train_discrete`, and it wasn't obvious if it should be updated or not, so I didn't change its behavior.

**Comment by hadley** [comment]
I'm reverting your PR because it breaks ggforce, and I see from the other thread in units it doesn't fix the motivating problem.
