### ISSUE TITLE
Add formatter for genomic distance (feature_request)

### ISSUE THREAD

**Issue by davidmasp** [r-lib/scales#171]
Hi,

Working in bio-things I often end up plotting genomic coordinates (base-pairs) (see [this](https://en.wikipedia.org/wiki/Base_pair) ) and thought it could be really useful to me (and hopefully to others) to add a genomic distance formatter. 

It would be very similar to the byte formatter I think. 

![image](https://user-images.githubusercontent.com/14033475/44098655-0f3e7ebe-9fe1-11e8-87e4-a20c459d82f3.png)

This is a very minimal representation of a gene. Done with my scales fork ( https://github.com/davidmasp/scales/tree/genomic_format ).

**Comment by davidmasp** [comment]
On second thought, this could be easily be wrapped up around `unit_format` I guess, and it may be too specific for the intention of the package, so sorry for bothering. I kind of liked the way `number_bytes` automatically selects the unit.

**Comment by dpseidel** [comment]
Thanks @davidmasp. You're right currently the scale above is currently easily achieved manually with `unit_format()`, however the automatic nature you like about `number_bytes()` is something we are currently working on incorporating into standalone functions that would allow suffix and scale to vary based on magnitude within a single scale-- see discussion on PR #164. So while we may not decide to add a genetic formatter per se,  I'll keep your use case in mind when I get a chance to get back to and finish #164.

**Comment by davidmasp** [comment]
Great, sounds good. Thanks for the quick reply 😄
