### ISSUE TITLE
scales 1.0.0 log_breaks makes for inferior visual test (numeric-log.svg) in ggplot2

### ISSUE THREAD

**Issue by dpseidel** [r-lib/scales#179]
While approving the changes to ggplot2's visual tests (tidyverse/ggplot2#2842), @hadley requested that we review the change in `numeric-log.svg` cause by the improved `log_breaks()` functionality introduced in scales 1.0.0

### This was the plot rendered with scales 0.5.0:
![log_breaks scales 0.5.0](https://user-images.githubusercontent.com/16724456/45191624-4062f400-b1f9-11e8-91ba-8db3a86f8d51.png)

### This is the current plot with scales 1.0.0:
![log_breaks scales 1.0.0](https://user-images.githubusercontent.com/16724456/45191623-3f31c700-b1f9-11e8-89bc-729e67d605bf.png)

The scale is behaving as expected but the additional major tick lines does make for a visually busier grid, especially given the use of `theme_test()` by default.

**Comment by mikmart** [comment]
Just as a bit of an "outsider" view, I like that the new base 10 log grid is consistent with the linear grid. The visual tests have 1 and 10 000 on the log scale plot (so 5 orders of magnitude), resulting in 5 major grid lines; which is also what you would get when plotting 1 and 5 on a linear scale.

The new log-grid is certainly busier, but if it were to be adjusted, for the sake of consistency the same adjustment should also apply to a linear grid.

**Comment by hadley** [comment]
Hmmm looking at it again, I don't see what my problem was - the new display looks better to me. Maybe I got confused between the new and old plots?
