### ISSUE TITLE
Geographic coordinate formatters

### ISSUE THREAD

**Issue by mikmart** [r-lib/scales#180]
Following the degree formatter (#159) in #178, it feels like a natural extension would be to add a family of geographic coordinate formatters (wrapping `degree_format()`) to automatically determine the appropriate unit to use, given latitudes and longitudes. Something like this:

``` r
library(scales)

latitude(seq(-20, 20, by = 10))
#> [1] "20°S" "10°S" "0°N"  "10°N" "20°N"
longitude(seq(-20, 20, by = 10))
#> [1] "20°W" "10°W" "0°E"  "10°E" "20°E"
```

I have a draft branch implementing these [here](https://github.com/mikmart/scales/tree/lat-long). Does this sound worth adding, or is it going too granular?

Created on 2018-09-07 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0.9000).

**Comment by hadley** [comment]
I'm not sure how useful it will be given that ggplot2 currently mostly depends on sf for these calculations.

**Comment by mikmart** [comment]
Fair enough, I'll shelve this for now.
