### ISSUE TITLE
Should format functions turn NAs into strings?

### ISSUE THREAD

**Issue by clauswilke** [r-lib/scales#187]
I just noticed that format functions turn `NA`s into strings instead of keeping them as `NA`. Is this as intended? It's particularly weird for the `dollar()` function.

``` r
x <- c(100, NA, 20000, NA, 1.5)
scales::comma(x)
#> [1] "100"    "NA"     "20,000" "NA"     "2"
scales::dollar(x)
#> [1] "$100.00"    "$NA"        "$20,000.00" "$NA"        "$1.50"
```

<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by clauswilke** [comment]
It's probably not feasible to change how all the formatting functions work, since somebody somewhere  likely depends on the conversion of `NA` to `"NA"`. But maybe adding an optional parameter to toggle `NA` formatting would make sense, e.g. `skip_NA`? It would be `FALSE` by default, indicating that `NA` should not be skipped, which is the current behavior.

**Comment by hadley** [comment]
I think they should stay as `NA` and something downstream should handle turning into `"NA"` if needed.

**Comment by clauswilke** [comment]
Ok, I'll look into preparing a PR.
