### ISSUE TITLE
width parameter for numeric scales

### ISSUE THREAD

**Issue by bhogan-mitre** [r-lib/scales#190]
I love the `width` parameter of `date_scales`, and I think it'd be helpful to provide a similar option for numeric scales.

You can manually provide a vector at the exact breaks of interest:
```
qplot(x = 1:10, y = 1:10, geom = "point") + scale_x_continuous(breaks = 1:10)
```

But that feels clunky if the range is not known in advance.  Now that I'm looking into it, it seems that the best workaround may be to leverage `fullseq` with parameter `size` equal to the desired width.
```
qplot(data = mpg, x = cty, y = hwy) + 
  scale_x_continuous(breaks = function(limits) fullseq(limits, size = 15))
```

Is there a way to more directly support a width parameter here?

**Comment by clauswilke** [comment]
Is this ggplot2 pull request related? https://github.com/tidyverse/ggplot2/pull/2334

**Comment by bhogan-mitre** [comment]
> Is this ggplot2 pull request related? [tidyverse/ggplot2#2334](https://github.com/tidyverse/ggplot2/pull/2334)

Yes, that it definitely related.  Although it seems like such a simple use case for a user to have to pass in their own function for.  (And of course, the PR is approaching its one year anniversary with no movement.)

What about a new function `numeric_breaks` to mimic this behavior from `date_breaks`?

**Comment by clauswilke** [comment]
I have no strong opinion on the best way to implement this. Just wanted to point out that there is an abandoned PR on this issue.

**Comment by dpseidel** [comment]
tidyverse/ggplot2#2334 has now been merged allowing functional limits to continuous scales. Does this solve your issue @bhogan-mitre? It seems only peripherally related to me. 

I don't have a strong opinion about the `numeric_breaks` suggestion. Seems like a small wrapper around existing `fullseq` functionality but it could be useful to some and is easily implemented. The name would definitely need to be more descriptive however -- perhaps `regular_breaks`? 

 @hadley what do you think about including something like this in scales?

**Comment by bhogan-mitre** [comment]
Thanks @dpseidel.  Yes, I agree that PR is only somewhat related.  

I am more concerned with breaks than limits.  My main issue is that for things that are inherently discrete, I typically want to override the breaks so that I'm not getting labels like 2.5 and 7.5.  Suppose I want to have breaks (and thus labels) at every integer, or multiples of 5, or whatever.  I get spoiled that this is so easy for date/time axes with the width parameter (e.g. `date_breaks = "2 weeks"`).  Breaks already accepts a function as input, so I could provide this myself.  But this seems like a common use case that could be handled more directly.

I'm unsure the best place for this, or if there is a clean way to expose it from ggplot2.  If there was a `regular_breaks` function, the usage would look like:
```
qplot(data = mpg, x = cty, y = hwy) + 
  scale_y_continuous(breaks = scales::regular_breaks(width = 5))
```

instead of
```
qplot(data = mpg, x = cty, y = hwy) + 
  scale_y_continuous(breaks = function(limits) scales::fullseq(limits, size = 5))
```

What do you think about exposing that via `ggplot2::continuous_scales` as well?  With a new `regular_breaks` parameter:
```
qplot(data = mpg, x = cty, y = hwy) + 
  scale_y_continuous(regular_breaks = 5)
```
or somehow overloading the `breaks` parameter with a keyword:
```
  scale_y_continuous(breaks = "every 5")
```

**Comment by dpseidel** [comment]
So it occurs to me now that this is much more related to the discussion of adding an `n_breaks` argument to continuous scales in ggplot2 (https://github.com/tidyverse/ggplot2/pull/3102). We actually just recently merged a change to scales that will make this possible (#197). It's not exactly what you're proposing but it likely will serve mostly the same purpose.  

I think it's unlikely that we would want to add an additional new argument to continuous scales in ggplot2 as each new argument/feature carries with it additional maintenance burden to an already large package. And given the pending change to ggplot2 and the exisiting `fullseq` functionality in scales, I would conservatively say that adding a `regular_breaks` function to scales is likely an unnecessary addition to the codebase. @thomasp85, can you offer a better sense of the future of this feature in ggplot2?

**Comment by thomasp85** [comment]
I don’t think this should be exposed as another argument personally. It would be pretty easy to make a dedicated scale for this sort of behaviour if passing in a function to breaks seems burdensome

**Comment by hadley** [comment]
Implemented as `breaks_width()`: https://scales.r-lib.org/reference/breaks_width.html
