### ISSUE TITLE
percent() returns "NA%" instead of returning NA

### ISSUE THREAD

**Issue by bkkkk** [r-lib/scales#193]
The following code:

`scales::percent(c(NA_real_, 0.1))`

returns:

`[1] "NA%"   "10.0%"`

**Comment by clauswilke** [comment]
I believe this was fixed in #188. Could you try with the github version of scales?

**Comment by bkkkk** [comment]
Works now, my apologies. Any idea when this will be released on CRAN? or am I missing something and it's already there?

**Comment by clauswilke** [comment]
I'm going to close this issue then. I don't know for when the next official scales release is planned. The version currently on CRAN doesn't have this fix yet.
