### ISSUE TITLE
Yeo-Johnson Transform

### ISSUE THREAD

**Issue by zamorarr** [r-lib/scales#196]
Hi `scales` devs - thanks for the great package. I would like to propose adding the [Yeo-Johnson](https://en.wikipedia.org/wiki/Power_transform#Yeo%E2%80%93Johnson_transformation) transform to complement the existing BoxCox and Modulus transforms. The Yeo-Johnson transform can be useful for pre-processing data and is already included in the `recipes` and `caret` packages. It would be great to  have it in this package to make visualization easy in `ggplot2`.

I'd be happy to submit a PR for review.

**Comment by dpseidel** [comment]
I'm happy to review a PR for this. @hadley do you think this is an appropriate addition?

**Comment by hadley** [comment]
Sure, seems reasonable.
