### ISSUE TITLE
`pseudo_log_trans` could provide better default breaks

### ISSUE THREAD

**Issue by bjedwards** [r-lib/scales#219]
By default, at least for `base=10`, `pseudo_log_trans` doesn't provide great default breaks.

Example:
```R
library(tidyverse)
library(scales)

# Random Log Normal
set.seed(8675309)
data <- tibble(x = rlnorm(1000, 0, 2))

ggplot(data, aes(x = x)) +
  geom_histogram() + 
  scale_x_continuous(trans = pseudo_log_trans(0.001, 10))
```

Which results in:
![image](https://user-images.githubusercontent.com/726274/63979315-2c557980-ca7e-11e9-84da-ea578b89ddf9.png)

Setting them to something more reasonable:
```R
ggplot(data, aes(x = x)) +
  geom_histogram() + 
  scale_x_continuous(trans = pseudo_log_trans(0.001, 10),
                     breaks=c(0, 0.01, 0.1, 1, 10, 100))
```

provides a slightly better set of breaks:

![image](https://user-images.githubusercontent.com/726274/63979419-69217080-ca7e-11e9-83d2-245eb2524305.png)

I thought that `trans_new` would be the solution and tried:

```R
plt <- function(sigma = 1, base = exp(1)) {
  trans_new(
    "pseudo_log",
    function(x) asinh(x / (2 * sigma)) / log(base),
    function(x) 2 * sigma * sinh(x * log(base)),
    breaks = log_breaks(n=5, base=base)
  )
}

ggplot(data, aes(x = x)) +
  geom_histogram() + 
  scale_x_continuous(trans = plt(0.001, 10))
```

But this raises the following error:

```
Error in if (max == min) return(base^min) : missing value where TRUE/FALSE needed
```

Which is occurring in [here in `log_breaks`](https://github.com/r-lib/scales/blob/7f6f4a52d56ac7f257496c8117553851a455732a/R/breaks.r#L67).

Not sure what they best path forward is or if this is actually expected behavior.

**Comment by hadley** [comment]
Unfortunately this is pretty low priority for us; I'd definitely review a PR that implemented better breaks but due to the very specialised nature of the transformation it's unlikely to be something we'd work on.

**Comment by jarodmeng** [comment]
`log_breaks` would work if you turn off `expand`.

```
ggplot(data, aes(x = x)) +
  geom_histogram() + 
  scale_x_continuous(trans = pseudo_log_trans(0.001, 10), breaks = log_breaks(base = 10), expand = c(0, 0))
```

However, `log_breaks` still wouldn't work if the range of `x` covers negative values, so the issue reported is only mitigated by using `log_breaks` + `expand`, but not totally solved.

**Comment by jmpanfil** [comment]
Can you clarify (or point me to the source code) to understand how `trans` and `breaks` work with each other? Does the data `x` get sent through each independently? Or something like `trans(x)` becomes the input to the `breaks` function?

**Comment by rseiter** [comment]
How about just modifying log_breaks to create something like this?

```
force_all <- function(...) list(...) # Helper function defined in scales

pseudo_log <- function (val, sigma = 1, base = exp(1)) {
  xval <- asinh(val/(2*sigma))/log(base)
}

#' Pseudo log breaks (integer breaks on pseudo log-transformed scales).
#'
#' @param n desired number of breaks
#' @param sigma scale factor of pseudo logarithm to use
#' @param base base of pseudo logarithm to use
#' @export
#' @examples
pseudo_log_breaks <- function(n = 5, sigma = 1, base = 10) {
  force_all(n, base)
  n_default = n
  function(x, n = n_default) {
    rng <- pseudo_log(range(x, na.rm = TRUE), sigma = sigma, base = base)
    min <- floor(rng[1])
    max <- ceiling(rng[2])

    if (max == min) return(base^min)

    by <- floor((max - min) / n) + 1
    breaks <- base^seq(min, max, by = by)
    relevant_breaks <- base^rng[1] <= breaks & breaks <= base^rng[2]
    if (sum(relevant_breaks) >= (n - 2)) return(breaks)

    # the easy solution to get more breaks is to decrease 'by'
    while (by > 1) {
      by <- by - 1
      breaks <- base^seq(min, max, by = by)
      relevant_breaks <- base^rng[1] <= breaks & breaks <= base^rng[2]
      if (sum(relevant_breaks) >= (n - 2)) return(breaks)
    }
    log_sub_breaks(rng, n = n, base = base)
  }
}

plt <- function(sigma = 1, base = exp(1)) {
  trans_new(
    "pseudo_log",
    function(x) asinh(x / (2 * sigma)) / log(base),
    function(x) 2 * sigma * sinh(x * log(base)),
    breaks = pseudo_log_breaks(n=5, sigma=sigma, base=base)
  )
}

ggplot(data, aes(x = x)) +
  geom_histogram() + 
  scale_x_continuous(trans = plt(0.001, 10))
```

![Rplot_pseudo_log_breaks](https://github.com/user-attachments/assets/011ba549-5cc6-41d1-9f1b-e9ae448f9142)
