### ISSUE TITLE
label_number_si does not use SI prefixes (Billion vs Giga)

### ISSUE THREAD

**Issue by zeehio** [r-lib/scales#234]
Thanks for this release. It looks like it delivers great improvements.

The `label_number_si()` uses [short scale (English) prefixes](https://en.m.wikipedia.org/wiki/Long_and_short_scales) instead of [SI prefixes](https://en.m.wikipedia.org/wiki/Metric_prefix). The naming is confusing, since with that function name I would expect labels like "1k, 1M, 1G".

In several European countries 1 billion is 1 million millions. As far as I know there is no SI agreement on what a billion is, and the SI recommends using metric prefixes (1G for 1E9).

Also, the documentation for that function states 10e9, when it means 1e9 ("e" means "multiplied by 10 to the power of").

Either there is a rationale I am missing or without a breaking change this behaviour will last for a long time... If that's the case I hope there is an early bugfix release that breaks backwards compatibility...

Thanks again!

**Comment by halldc** [comment]
I think it's worth renaming this function. To provide an SI prefix labeler, we'd need to add a lot more prefixes (e.g. milli- for 1e-3) and kilo- should be represented by a lowercase k (not uppercase K).

**Comment by davidchall** [comment]
I think it's worth renaming this function. To provide an SI prefix labeler, we'd need to add a lot more prefixes (e.g. milli- for 1e-3) and kilo- should be represented by a lowercase k (not uppercase K).

**Comment by teunbrand** [comment]
Related to this, aren't the 'prefixes' in actuality suffixes?

**Comment by davidchall** [comment]
They’re called prefixes because they go immediately before the SI unit. For example, the SI unit of length is the meter, so a thousand meters is a kilometer (km) and one thousandth of a meter is a millimeter (mm).

In the context of the scales package, these SI prefixes appear in the suffix component of the output, because the unit always comes after the value (e.g. 10 km).

**Comment by zeehio** [comment]
They are called prefixes in the international system of units because they are meant to be used before the unit (kilometer, hectometer, megabyte), it makes sense to me 🙂
