### ISSUE TITLE
Minor regression: numeric inputs to colour_ramp()

### ISSUE THREAD

**Issue by mitchelloharawild** [r-lib/scales#237]
Looks like the move to farver has introduced a minor regression.
I didn't see this in the NEWS, so I presume the change is unintended.

``` r
# CRAN v1.1.0
library(scales)
colour_ramp(1:5)(0.5)
#> Error in stats::approxfun(x_in, lab_in[, 1]): need at least two non-NA values to interpolate
```

``` r
# CRAN v1.0.0
library(scales)
colour_ramp(1:5)(0.5)
#> [1] "#00CD00"
```

<sup>Created on 2019-11-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by thomasp85** [comment]
Fixed in the new version of farver
