### ISSUE TITLE
Delete whitesapce in `demo_` ouput

### ISSUE THREAD

**Issue by enixam** [r-lib/scales#238]
When using `demo_continuous` (and other `demo_*` functions) to demonstrate ggplot2 style scales, whitespace / margin between code and scales generated can be pretty annoying:  
![95a00b9ee41bca3bfbb311c152a0799](https://user-images.githubusercontent.com/48123899/69793847-2b122500-1204-11ea-8174-a53dcac49de5.png)

Is there a way I can delete the whitespace ？

**Comment by hadley** [comment]
Yes, make your figure shorter
