### ISSUE TITLE
Inconsistent rounding `percent` when given array of values

### ISSUE THREAD

**Issue by bkkkk** [r-lib/scales#239]
Using `scales 1.1.0`:

I get the following, to my eyes, unexpected result:

```
> percent(c(0.11111))
[1] "11%"
> percent(c(0.11111, 0.11))
[1] "11.11%" "11.00%"
> percent(c(0.111, 0.11))
[1] "11.100%" "11.000%"
> percent(c(0.111, 0.111))
[1] "11%" "11%"
```

So the depending on how many digits I provide something else happens, but this only occurs with multiple values. If I only provide a single value the result is always `11%` no matter how many decimal digits are provided.

**Comment by hadley** [comment]
See the documentation for `accuracy`
