### ISSUE TITLE
Color interpolation in colour_ramp() can fail in some cases

### ISSUE THREAD

**Issue by clauswilke** [r-lib/scales#241]
The colorspace package is [failing testing on CRAN](
https://r-forge.r-project.org/R/?group_id=20&log=check_x86_64_windows&pkg=colorspace&flavor=patched) apparently caused by this line in the code:
https://github.com/r-lib/scales/blob/a33f8ef9d2930f4940f9c694ba6ba79480965cec/R/colour-ramp.R#L58

This is the error:
``` r
> ### ** Examples
> 
> # adapted from stackoverflow: https://stackoverflow.com/a/20127706/4975218
> 
> library("ggplot2")
> 
> # generate dataset and base plot
> set.seed(100)
> df <- data.frame(country = LETTERS, V = runif(26, -40, 40))
> df$country = factor(LETTERS, LETTERS[order(df$V)]) # reorder factors
> gg <- ggplot(df, aes(x = country, y = V, fill = V)) +
+   geom_bar(stat = "identity") +
+   labs(y = "Under/over valuation in %", x = "Country") +
+   coord_flip() + theme_minimal()
>   
> # plot with default diverging scale
> gg + scale_fill_continuous_diverging()
Error in if (!alpha || all(lab_in[, 4] == 1)) { : 
  missing value where TRUE/FALSE needed
Calls: scale_fill_continuous_diverging ...  -> ggproto ->  -> colour_ramp
Execution halted
```

Strangely this error occurs [only on Windows.](https://CRAN.R-project.org/web/checks/check_results_colorspace.html)

It is unclear to me why this happens, since colorspace calls `gradient_n_pal()` which then calls `colour_ramp()` with default arguments here:
https://github.com/r-lib/scales/blob/a33f8ef9d2930f4940f9c694ba6ba79480965cec/R/pal-gradient.r#L16

However, in either case, it looks to me like line 58 in `colour_ramp()` is sensitive to missing `alpha` arguments and would be safer if it read:
``` r
  if (!isTRUE(alpha) || all(lab_in[, 4] == 1)) { 
```

**Comment by clauswilke** [comment]
Based on an analysis of the possible causes of the error message seen (below), I now think the problem lies in the argument to the `any()` function. If `lab_in[, 4] == 1` ever evaluates to `NA`, then `any()` returns `NA` and we see the error message shown.

@thomasp85 Are there any conditions under which `farver::decode_colour(colors, alpha = TRUE, to = "lab")` could return `NA` in the fourth column?

``` r
f <- function(alpha = TRUE, x = 1) {
  if (!alpha || any(x == 1)) print("test")
}

f(alpha = NULL)
#> Error in !alpha: invalid argument type
f(alpha = NA)
#> [1] "test"
f(x = NULL)
f(x = numeric(0))
f(x = NA)
#> Error in if (!alpha || any(x == 1)) print("test"): missing value where TRUE/FALSE needed

any(NULL)
#> [1] FALSE
any(numeric(0))
#> [1] FALSE
any(NA)
#> [1] NA
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Suggested fail-safe revision of line 58 in `colour_ramp()`:
``` r
  if (!isTRUE(alpha) || all(lab_in[, 4][!is.na(lab_in[, 4])] == 1)) { 
```

Examples:
``` r
f <- function(alpha = TRUE, x = 1) {
  if (!isTRUE(alpha) || any(x[!is.na(x)] == 1)) print("test")
}

f(alpha = NULL)
#> [1] "test"
f(alpha = NA)
#> [1] "test"
f(x = NULL)
f(x = numeric(0))
f(x = NA)
```

<sup>Created on 2019-12-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Here is a simple reprex that results in the same error.

``` r
library(scales)

colour_ramp(c("red", NA, "blue"))
#> Error in if (!alpha || all(lab_in[, 4] == 1)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
Any invalid element will get converted to an Na row

**Comment by clauswilke** [comment]
Yes, I think the behavior of `decode_colours()` is reasonable and `colour_ramp()` has to be able to handle `NA`s. It's still strange that colorspace only has problems on Windows, but maybe it's a rounding error where colors are just slightly pushed out of gamut on Windows and not on Unix.

**Comment by thomasp85** [comment]
Out-of-gamut colours are not really possible with `decode_colours()` and if, they would just be capped to the channel range. Do you have a reprex for the behaviour?

**Comment by thomasp85** [comment]
To be more specific, `decode_colour()` should only return `NA` if the input string is invalid

**Comment by clauswilke** [comment]
Sorry, I think I was mixing two separate things that confused the issue. First, for the purposes of `colour_ramp()`, the reprex is simply: `colour_ramp(c("red", NA, "blue"))` This code should not error out, but it does.

Second, I was just pondering why the colorspace package would send `NA` input to `colour_ramp()`, and that's where my out-of-gamut comment applied. Colorspace itself uses calculated colors, and it can encounter out-of-gamut situations and may create `NA`s in that case. (I'm not sure; I'm just speculating here. The problem is we don't have a reprex for this second case, only the failure on CRAN that nobody has recreated yet on their local machine.)

**Comment by statibk** [comment]
Thanks for the discussion so far. I have asked the CRAN team now whether they already had a look at what is going wrong specifically on Windows. I will let you know if this leads to a reproducible example.

As for Claus' simple example (thanks!) I investigated what happened in `scales` up to version 1.0.0:

    scales::colour_ramp(c("red", NA, "blue"))(0:4/4)
    ## [1] "#FF0000"   "#FF9E8180" "#FFFFFF00" "#B38BFF80" "#0000FF"

Thus, NA behaved like fully transparent white. This was presumably due to the behavior of `col2rgb()`:

    col2rgb(NA, alpha = TRUE)
    ##       [,1]
    ## red    255
    ## green  255
    ## blue   255
    ## alpha    0

In contrast:

    farver::decode_colour(NA, alpha = TRUE)
    ##       r  g  b alpha
    ## [1,] NA NA NA    NA

I think that the latter is more intuitive but as Claus pointed out `colour_ramp()` needs to be adjusted correspondingly.

**Comment by thomasp85** [comment]
Yeah, I think I'm going to insist on NAs turning to NAs in farver, so we should fix this in scales

**Comment by thomasp85** [comment]
Or, I can make it a switch in `decode_colour()` which would not incur a performance penalty in scales

**Comment by statibk** [comment]
I would prefer an explicit fix in `scales` because treating `NA`s like transparent white is probably not the ideal solution.

**Comment by thomasp85** [comment]
Sure, scales will need to be updated to use the new switch in farver, but I think the treatment in scales is as it should (i.e. in line with how base R treats NA as a colour)

If you don't want scales to throw an error it has to interpret NA to some colour and transparent white is pretty standard (e.g. when you specify "no colour" in most drawing library it resolves to transparent black or transparent white)

If you mean that scales should drop NA's automatically, this would be a breaking change and it would be better if you removed them before going into scales

**Comment by thomasp85** [comment]
I have added a `na_value` argument to `decode_colour()`. Setting this to `#ffffff00` will make it behave as `col2rgb()`, thus fixing this issue. If you want a different handling of `NA` I think it should be defined in colorspace and not scales as it goes against the standard interpretation (whether we like it or not)

**Comment by clauswilke** [comment]
I think using an `na_value` argument is a principled approach in line with how similar problems are solved elsewhere in ggplot2. One minor suggestion: Add the same argument to `colour_ramp()`, so it can be carried through.

**Comment by thomasp85** [comment]
I'll be releasing a minor update of farver soon with all this and we can then update scales to restore the old behaviour (and make it accessible to users potentially)

**Comment by petrakle** [comment]
I get the error `Error in if (!alpha || all(lab_in[, 4] == 1)) { : 
  missing value where TRUE/FALSE needed` on Mac OS Mojave, when trying to use `scales` package to rescale values in `scale_fill_gradientn()`.

**Comment by thomasp85** [comment]
Can you provide a reprex?
