### ISSUE TITLE
Expose n_col in show_col

### ISSUE THREAD

**Issue by dmi3kno** [r-lib/scales#250]
Today in `show_col()`
```r
show_col <- function(colours, labels = TRUE, borders = NULL, cex_label = 1) {
  n <- length(colours)
  ncol <- ceiling(sqrt(n))
  nrow <- ceiling(n / ncol)
...
```
I am sometimes printing multiple color palettes and would like to control how they are displayed. Could we please expose optional `ncol` argument with default value as it is today.
```r
show_col <- function(colours, labels = TRUE, borders = NULL, 
                    cex_label = 1, ncol = ceiling(sqrt(length(colours)))) 
```
Alternative, but perhaps equally useful feature could be to allow passing a character matrix (vector with `dim` attribute) and let that control the shape of the printed palette. (I don't know if you considered showing labels, if a vector is named)

I am also a little concerned about the margins of the plot when number of colors is small. It seems like we could make margins tighter by calculating anticipated size of the plot. 

Let me know if you would like a PR with this.

**Comment by hadley** [comment]
A PR would be great, thanks!
