### ISSUE TITLE
Function "doColorRamp()" not found in version 1.1.0 

### ISSUE THREAD

**Issue by nicocriscuolo** [r-lib/scales#254]
I currently have a Leaflet map in my shiny app that needs the **scales** package as dependency when I add my custom legend to the leaflet object.

If I upgrade the scales package (version 1.0.0) to the latest version (1.1.0), my Leaflet object is not rendered when using the same exact functions to build my legend. The error reports that the function `doColorRamp()` is not found (but apparently this is not a function that I can call from the package). Just if I downgrade to the 1.0.0 version things start working again.

Thank you for your help.

**Comment by clauswilke** [comment]
This is almost certainly a bug in the Leaflet map and you should raise the issue with whoever wrote that code. `doColorRamp()` was an internal function that was deleted in version 1.1.0. If the Leaflet map code is looking for this function, it means that either the code is inappropriately using non-exported functions, or it is precalculating and caching closures across installations. Both would be problematic coding practices.

One thing that might help, though, is to reinstall the leaflet package from source after you've installed scales 1.1.0. This may resolve the issue.

**Comment by nicocriscuolo** [comment]
Thanks for the answer. Installing the Leaflet package from source did not help, I'm gonna raise the issue in the Leaflet GitHub page.

Thanks.
