### ISSUE TITLE
Documentation displays multiple warnings for label_dollar

### ISSUE THREAD

**Issue by brunocarlin** [r-lib/scales#263]
<https://scales.r-lib.org/reference/label_dollar.html>

<details>
The code that produces the warnings is

```
euro <- dollar_format(
  prefix = "",
  suffix = "\u20ac",
  big.mark = ".",
  decimal.mark = ","
)
demo_continuous(c(1000, 1100), labels = euro)
```

It works fine on my current R env

``` r
library(scales)

euro <- dollar_format(
  prefix = "",
  suffix = "\u20ac",
  big.mark = ".",
  decimal.mark = ","
)
demo_continuous(c(1000, 1100), labels = euro)
#> scale_x_continuous(labels = euro)
```

![](https://i.imgur.com/R4fhijR.png)

<sup>Created on 2020-03-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
</details>

**Comment by hadley** [comment]
I can't see any way to fix this in scales, but I think we can fix upstream in pkgdown.
