### ISSUE TITLE
Document all oob_ functions in one file

### ISSUE THREAD

**Issue by hadley** [r-lib/scales#267]
Since they're all quite simple

**Comment by clauswilke** [comment]
@teunbrand Are you willing to take this on?

**Comment by teunbrand** [comment]
Sure, seems a good idea to me. I'll write something up!

**Comment by teunbrand** [comment]
A thought occurred to me that is tangentially related to this issue. Currently there are two versions of squishing values inside the range: `oob_squish()` and `oob_squish_infinite()`. 

We could consider splitting out `oob_squish` to `oob_squish_finite()`, with the current default behaviour, and `oob_squish_all()`, which would behave as `oob_squish(x, only.finite = FALSE)`. 

I may assume wrongly here, but my reasoning is that if the main user interaction with these functions is to pass these as `oob` arguments to continuous/binned scales, then the `only.finite` argument to `oob_squish()` is impractical to set. You cannot —or I wouldn't immediately know how to— pass this function with that argument without a small wrapper; for example `function(x, range){oob_squish(x, range, only.finite = FALSE)}`. Then, it would be more convenient to have a dedicated function for this.

I could post this as a seperate issue and weave this into the PR if you think that makes sense.

**Comment by clauswilke** [comment]
This makes sense to me. Would you keep `squish` as an alias to `oob_squish_finite` for backwards compatibility?

**Comment by hadley** [comment]
Fixed in #268
