### ISSUE TITLE
Issue with rescale_pal

### ISSUE THREAD

**Issue by vsocrates** [r-lib/scales#276]
I imagine this is just something I'm doing wrong, but I'm having an issue with the basic use of `rescale_pal`. I'm using `scales version scales_1.1.0`. 

I get the following output given -1 as the input:

```
> rescale_pal(range = c(0.1, 1))(-1)
[1] -0.8
```

This seems like not the right answer. I imagine I either want 0.1 or some scaled value between 0.1 and 1 according to the documentation. Is this a bug?

**Comment by hadley** [comment]
The expectation is that all the values lie in the supplied `range`. Maybe you want just `rescale()`?
