### ISSUE TITLE
number(accuracy = NULL) heuristic too precise?

### ISSUE THREAD

**Issue by nicolaspayette** [r-lib/scales#279]
``` r
scales::number(c(10, 20, 30))
#> [1] "10" "20" "30"
scales::number(c(5, 10, 15))
#> [1] "5.0"  "10.0" "15.0"
```

When the smallest interval is >= 1 and < 10, the heuristic computes an accuracy of 0.1.

This might be the intended behaviour, but I find it puzzling: why would the extra decimal be desirable?

The question [has been raised in passing before](https://github.com/r-lib/scales/issues/251#issuecomment-586699978), but I didn't find any other discussion.

If this behaviour is modified, it might also make sense to change the default in `label_number_si()` to `accuracy = NULL`, since the current default of `accuracy = 1` gives results like:

``` r
scales::label_number_si()(c(1.5E6, 2E6, 2.5E6))
#> [1] "2M" "2M" "2M"
```

**Comment by davidchall** [comment]
@nicolaspayette - Please note that #235 changes the default of `label_number_si()` to `accuracy = NULL`.

**Comment by nicolaspayette** [comment]
@davidchall, #235 looks fantastic. And maybe have `accuracy = NULL` as a default will bring more attention to the present issue.
