### ISSUE TITLE
trans_new manpage link missing

### ISSUE THREAD

**Issue by SimonDedman** [r-lib/scales#285]
Hi folks.
In v.1.1.1 there is no link from the main/index help page for the package, to trans_new.
![image](https://user-images.githubusercontent.com/4599748/87721520-68afc800-c76b-11ea-8f83-27f3ecd87702.png)

It is linked to from (e.g.) scale_continuous, trans section.
I'm not sure if this is true for other functions in the package. I thought these page links were generated automatically...?
Thanks

**Comment by hadley** [comment]
Yes, because it's mark as internal.
