### ISSUE TITLE
scales v1.1.1.: pal_hue() does not use argument 'h.start' anymore

### ISSUE THREAD

**Issue by aalucaci** [r-lib/scales#288]
The pal_hue() function does not use the argument 'h.start' anymore.
Compare:

https://github.com/r-lib/scales/blob/v1.1.1/R/pal-hue.r

with

https://github.com/r-lib/scales/blob/v1.1.0/R/pal-hue.r

'h.start' is not applied anymore in the latest version (v1.1.1). 

If this was by intention, my guess is that 'h.start' should also be removed from the arguments lists, since it does not do anything.
Otherwise, this probably shows the need of introducing a test showing that the argument is indeed used.

Kind regards,
Angela

**Comment by sebschub** [comment]
As shown in https://github.com/tidyverse/ggplot2/issues/4163#issue-674235219, this produces misbehaviour in ggplot.

**Comment by hadley** [comment]
Minimal reprex:

``` r
library(scales)
hue_pal()(4)
#> [1] "#F8766D" "#7CAE00" "#00BFC4" "#C77CFF"
hue_pal(h.start = 90)(4)
#> [1] "#F8766D" "#7CAE00" "#00BFC4" "#C77CFF"
```

<sup>Created on 2022-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
