### ISSUE TITLE
Error displaying very large numbers

### ISSUE THREAD

**Issue by NunoSempere** [r-lib/scales#295]
ggplot2's scales fail when displaying very large numbers in their scales, and this seems to be a problem in the scales package. 

Example in ggplot2
```r
(x <- runif(10))
#  [1] 0.4156626 0.7514519 0.8369314 0.4988923 0.2471835 0.4177872 0.3411027
#  [8] 0.2414736 0.8016840 0.1863059

(y <- runif(10) * (10^250))
#  [1] 8.342025e+249 4.522077e+249 6.600850e+248 3.022238e+248 4.615520e+249
#  [6] 7.775300e+249 9.199057e+249 8.390373e+249 6.644477e+249 1.806842e+249

qplot(x, y)
# Error in if (score > best$score && (!only.loose || (lmin <= dmin && lmax >=  : 
#   missing value where TRUE/FALSE needed
```

Example in the labeling packages which `scales` imports:

```r
labeling::extended(1e250, 2e250, 3, only.loose = FALSE)
#> Error in if ((w[1] * sm + w[2] * cm + w[3] * dm + w[4]) < best$score) break: missing value where TRUE/FALSE needed
```

From a [previous issue](https://github.com/tidyverse/ggplot2/issues/4207) on ggplot2:
> {labeling} seems unmaintained, so {scales} may have to reconsider importing it. The {labeling} code is licensed under MIT, so it could just be copied to {scales} and then fixed.

**Comment by NunoSempere** [comment]
I sent a message to the package maintainer with a potential solution. At some point, the upper and lower boundaries are squared, and this breaks the maximum R integer size. Will follow up in a month or so.

**Comment by clauswilke** [comment]
Could you post your proposed solution here also so it's recorded? My hopes for getting this fixed in {labeling} are not that high. There hasn't been a new release in over six years, and the maintainer was informed of this specific issue over three years ago.

**Comment by NunoSempere** [comment]
Sure. In `labeling.R`, in the `extended` function, add

```
  if((dmax - dmin) > 1e+155) {
    #if the range is too large
    #let seq generate some equally spaced steps.
    return(seq(from=dmin, to=dmax, length.out=m))
  }
```

Alternatively, go through the .coverage functions. Check that for large numbers they tend to return 1 (I'm not completely sure of this), and if so, add 

```
  if((dmax - dmin) > sqrt(.Machine$double.xmax) {
    # if the range is too large for the normal computation
    # but doesn't yet exceed the maximum integer size 
    # return 100% coverage
    return(1)
  }
```

respectively, 
```
  if(range > sqrt(.Machine$double.xmax)) {
    # if the range is too large for the normal computation
    # but doesn't yet exceed the maximum integer size yet
    # return 100% coverage
    return(1)
  }
```

**Comment by NunoSempere** [comment]
So what's the modus operandi for an unmaintained repository? Fork it and then resubmit to cran?

**Comment by NunoSempere** [comment]
The author of the labeling package has adopted the above solution. This issue is now solved.

**Comment by NunoSempere** [comment]
Oh no they haven't

**Comment by NunoSempere** [comment]
Oh no they haven't.

**Comment by NunoSempere** [comment]
The issue is now fixed in the latest version of the labeling package, and hence in the scales package, and hence in ggplot2. Tested with:

```
install.packages("ggplot2")
library(ggplot2)

(x <- runif(10))
(y <- runif(10) * (10^250))
qplot(x, y)
```
