### ISSUE TITLE
Add inverse hyperbolic sine transformation

### ISSUE THREAD

**Issue by frederikziebell** [r-lib/scales#297]
Sometimes it's nice to have a 'log'-transformation that also works for negative values to have points more evenly spread-out:

```
ihs <- function(x){log(x+sqrt(x^2+1))}
ihs_trans <- scales::trans_new(name="ihs",transform=ihs, inverse=sinh)

set.seed(1)
data <- tibble(
  x=runif(10^4),
  y=rnorm(10^4)
)

data %>% 
  ggplot(aes(x,y)) +
    geom_point(alpha=.7) +
    ggtitle("regular")

data %>% 
  ggplot(aes(x,y)) +
    geom_point(alpha=.7) +
    scale_y_continuous(trans=ihs_trans) +
    ggtitle("ihs")
```

![image](https://user-images.githubusercontent.com/28304028/95364269-eac60d80-08d0-11eb-887b-490f5f55c1bd.png)
![image](https://user-images.githubusercontent.com/28304028/95364289-f1548500-08d0-11eb-8fef-268d152e93fd.png)

**Comment by thomasp85** [comment]
Fixed by #360
