### ISSUE TITLE
Feature request: flexibility of date and time transformations w.r.t. numeric input.

### ISSUE THREAD

**Issue by teunbrand** [r-lib/scales#298]
Originally discussed in https://github.com/tidyverse/ggplot2/issues/980#issuecomment-708960353; it seems as there is some need for flexibility of date and time transformations. These transformations are currently harder to program with than plain numerical transformations, as the date/time transformations have strict requirements on the class of the input data. 

@yutannihilation made two excellent [suggestions](https://github.com/tidyverse/ggplot2/issues/980#issuecomment-709210316) which I'll repeat here.

1. Let the `domain` part of the transformation be of the same class as the expected input data. This in particular would allow a solution to a longstanding [issue in ggplot2](https://github.com/tidyverse/ggplot2/issues/980).
2. Let `date_trans()$transform()` and `time_trans()$transform()` accept numeric values. This would solve the aforementioned issue, as well as some others.

I understand that the class requirements protect against unintentional mistakes so I'd like to mention a 3rd idea.

3. Add `...` arguments to all `trans$transform()` arguments and in addition a `force` argument to the date/time transforms. The logic then could be as follows:

```
function(x, force = FALSE, ...)  
{
  if (!inherits(x, "Date") & !force) {
    stop("Invalid input: date_trans works with objects of class Date only", 
         call. = FALSE)
  }
  structure(as.numeric(x), names = names(x))
}
```

This would allow only the transformation of intentional numeric values while still raising the error upon unintentional input.

Thanks for reading!

**Comment by teunbrand** [comment]
There is a case to be made for handling non-finite input to date/time transformations too, see https://github.com/tidyverse/ggplot2/issues/4308 or https://stackoverflow.com/questions/67177555/while-adding-a-semi-transparent-layer-to-background-image-in-r-getting-error-in?noredirect=1.

**Comment by hadley** [comment]
I think I'd need to see a concrete implementation to understand what you're suggesting here. My main worry is (e.g.) accidentally passing a date to date-time transformer, so you get number of days instead of number of seconds.

**Comment by hadley** [comment]
After reading the original issue, I think the easiest fix for the original problem is to give the domain the correct type.
