### ISSUE TITLE
Make sure `log10_trans` can calculate breaks for ranges outside of it's domain

### ISSUE THREAD

**Issue by thomasp85** [r-lib/scales#307]
This is a transfer of https://github.com/tidyverse/ggplot2/issues/2454

**Comment by tdhock** [comment]
hi! I am getting this issue too. Here is another way to generate the issue, https://www.anycodings.com/1questions/3904934/r-selective-finite-number-error-when-applying-log-scale
```r
> ggplot()+geom_line(aes(x,y),data=data.frame(x = c(500, 525, 500, 525), y = c(0.070860012, 0.052973494, 6.91685849999998e-310, 4.68262549999999e-310)))+scale_y_log10()
Error in seq.default(min, max, by = by) : 'from' must be a finite number
```
