### ISSUE TITLE
Add lifecycle badges to retired functions

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/scales#308]
Some of the labeling functions (e.g. `percent()`) are noted as "retired". It would be nice to add lifecycle badges to them that show on top of the documentation as it's easy to miss the "Old interface" note. However, I believe this means the documentation for old interface functions would need to be separated from new ones, e.g. `label_percent()`.

**Comment by hadley** [comment]
And update to superseded
