### ISSUE TITLE
Feature request: Reverse log transformation

### ISSUE THREAD

**Issue by teunbrand** [r-lib/scales#313]
Hello there,

I thought it might be a convenience to some if a reverse log transformation function would exist in the scales package. Typical usage of these kinds of transformations would be in [manhattan plots](https://en.wikipedia.org/wiki/Manhattan_plot) or [volcano plots](https://en.wikipedia.org/wiki/Volcano_plot_(statistics)).

Concretely, I'm proposing something like the following:
``` r
library(scales)

revlog_trans <- function(base = 10) {
  force(base)
  trans = function(x) {-1 * log(x, base)}
  inv = function(x) {base ^ (-1 * x)}
  trans_new(
    paste0("rev-log-", format(base)),
    trans, inv, log_breaks(base = base),
    domain = c(1e-100, Inf)
  )
}

demo_continuous(c(1, 1e-7), trans = revlog_trans())
#> scale_x_continuous(trans = revlog_trans())
```

![](https://i.imgur.com/uKDafY1.png)

<sup>Created on 2021-06-25 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

If you think this is a good addition to the scales package, I could prepare a PR with the above transformation for review.
Thanks for considering!

**Comment by hadley** [comment]
Hmmm, I think this would be simpler to discover as a `reverse` argument to `log_trans()` and friends? Do you want to do a PR?

**Comment by hadley** [comment]
The other idea that occurred to me in #287 is to create a generic mechanism for composing transformations.

**Comment by teunbrand** [comment]
Yeah that seems a more general solution than tailoring a bunch of transformations to also have reversed variants.

**Comment by hadley** [comment]
Ok, lets close this issue and I'll pursue the composition idea.
