### ISSUE TITLE
Problems combining label_date_short with guide_axis(n.dodge = 2)

### ISSUE THREAD

**Issue by TonyLadson** [r-lib/scales#315]
When combining label_date_short() with guide_axis(n.dodge = 2), the dodged months end up below the year.  The expected behaviour was to have the dates dodging over 2 lines with year below. 
![Rplot](https://user-images.githubusercontent.com/1966541/128621061-a5ede71d-6005-4297-a43d-f0cb9a37f351.png)

```
xdf = tibble(xdate = seq(as.Date('2000-01-01'), by = '1 month', length.out = 14), y = rnorm(14))
xdf %>% 
  ggplot(aes(xdate, y)) +
  geom_point() +
  scale_x_date( date_breaks = '1 month', guide = guide_axis(n.dodge = 2), labels = scales::label_date_short())
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: resolving this interaction between dodging and `label_date_short()` would be a lot of work. You might consider making your own variant of `label_date_short()` that adds the additional newlines that you need. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
