### ISSUE TITLE
Please don't retire number(), percent(), comma(), and the like

### ISSUE THREAD

**Issue by donboyd5** [r-lib/scales#318]
I understand why you are retiring `number_format()`, `comma_format()`, etc. in favor of `label_number()`, `label_comma()`, etc.

However, if I understand the documentation properly, you also intend to retire `number()`, `comma()`, etc. I hope not. These functions are different because they accept a numeric input, and return a value rather than a function. I find them very useful when writing inline code in an `Rmarkdown` document, to insert formatted numeric results. Versions of the formatting functions that do not accept a numeric input and that return functions won't work as easily for this. There are workarounds, of course, but it would be nice to still be able to use the existing `number()`, `comma()`, etc. functions.

Thanks for considering this.

**Comment by hadley** [comment]
These functions are unlikely to ever go away, but be aware that you using them "off-label" because they were designed specifically to support ggplot2, not for general number formatting purposes where ever you might need them.
