### ISSUE TITLE
label_number_auto() fails on certain specific values

### ISSUE THREAD

**Issue by davidski** [r-lib/scales#321]
Under scales 1.1.1, `label_number_auto()` fails on certain specific numbers.

``` r
dat <- c(1636500, 30925005)

#works
scales::label_number_auto()(dat)
#> [1] "1 636 500"  "30 925 005"

#fails
scales::label_number_auto()(dat[2])
#> Error in apply(labels, 1, shortest): dim(X) must have a positive length

#fails
scales::label_number_auto()(30925005)
#> Error in apply(labels, 1, shortest): dim(X) must have a positive length
```

I'm specifically trying to apply `label_number_auto()` to a one row tibble with some of these problematic values in it via `across()`.

Debugging this, it looks like in the `format_shortest` call:

https://github.com/r-lib/scales/blob/9c5a00d66d3536e17f130abf50af9c3a61e1059d/R/label-number-auto.R#L53-L57

...the `labels` object is getting passed as a vector, which `apply` fails on. Some testing with ```   if (is.null(dim(labels))) {
      labels <- matrix(labels, nrow = 1)
    }``` looks like a possible work around, but the threads on how apply deals with vectors is a bit of a mystery to me.

Please let me know if I can add anything to help clarify this issue. Thanks!

**Comment by karawoo** [comment]
Thanks for the report and for investigating the issue, you are right that when there are multiple breaks `vapply()` is returning a matrix, but when there's only one it's returning a character vector which causes `apply()` to fail. I think this error would occur anytime you try get labels for a number greater than 1e+06.
