### ISSUE TITLE
Feature request: Clarify that scales have been squished/censored with legend prefix & suffix

### ISSUE THREAD

**Issue by adamkemberling** [r-lib/scales#326]
The out of bounds handling functions like `oob_squish` are very helpful, but is there a way to indicate that the values have been truncated in the legend? Something like:

`oob_squish(bound_affix = c("<", "+"))`

That would add the prefix `<` to the lower limit and add the suffix `+` to the upper limit?

I find myself using these functions often when I need a diverging color palette and want to center it on 0.  However, when the data has large outliers the colors become washed out without this step. It seems misleading to not acknowledge that the data falls beyond the range on the scale.

The desired functionality would resemble how `label_pvalue()` behaves, only without changing the original limits.

Thanks again for the package, it has been tremendously helpful.

**Comment by hadley** [comment]
Unfortunately there's no way to do this with ggplot2's current design.
