### ISSUE TITLE
rescale_short_scale() and rescale_long_scale() aren't available

### ISSUE THREAD

**Issue by campbead** [r-lib/scales#328]
I'm testing out different ways to label dollar amounts.  

The [documentation says](https://scales.r-lib.org/reference/label_dollar.html) `rescale_short_scale()` and `rescale_long_scale()` are two most common scales are provided to `rescale_large` option in the `label_dollar()` function.

However running this code:

```
library(scales)

my_dollar <- label_dollar(
  rescale_large = rescale_short_scale()
)
```

Results in an error:
```
Error in rescale_short_scale() : 
  could not find function "rescale_short_scale"
```

Have these functions be depreciated?

**Comment by dpseidel** [comment]
Hi @campbead!

These functions are available in the development version. To use them, be sure to install from github: `remotes::install_github("r-lib/scales")`
