### ISSUE TITLE
Rename `label_dollar` to `label_currency`

### ISSUE THREAD

**Issue by pwseo** [r-lib/scales#344]
Shouldn't `label_dollar` be renamed `label_currency`? I know it is functionally the same, but such a name would instantly tell the programmer that multiple currencies are probably supported, prompting one to read the documentation on how to specify them, instead of searching (for example) for a `label_euro`.

**Comment by clauswilke** [comment]
I fully agree with this comment. I taught this recently in the classroom and it was clear that the students were very confused when I was using a function `label_dollar` to create all sorts of different labels.

**Comment by olivroy** [comment]
I think this is great. Maybe it would be great that label_currency to be locale dependant (like label_date() that creates the scales in your system's language by default

**Comment by thomasp85** [comment]
@olivroy I don't think that is a good idea as it is much more normal to work with data in a currency that is not your own compared to using a date format different from your locale
