### ISSUE TITLE
Snapshot test is locale dependent

### ISSUE THREAD

**Issue by johanneskoch94** [r-lib/scales#347]
Hi, 
testing fails on my machine, due to a different locale that prints out "Okt" instead of "Oct", the latter of which is expected in the snapshot. This concerns line 34 and 41 specifically. I guess `withr::local_locale()` would do the trick, but since it's not being imported I'm not sure what the best solution is. Just wanted to let you know. Thanks for all the amazing packages!
https://github.com/r-lib/scales/blob/a2552d2aa1f04e1b394a7f7a23ecda92570a5971/tests/testthat/test-label-date.R#L27-L44

**Comment by mjskay** [comment]
FWIW {testthat} imports {withr}, so adding {withr} to Suggests in {scales} wouldn't add a dependency that's not already downstream.
