### ISSUE TITLE
Feature Request: Apply different OOB functions to lower and upper limits

### ISSUE THREAD

**Issue by mdefende** [r-lib/scales#351]
I'm wanting to create a plot that censors values below the lower limit but squishes values above an upper limit. As far as I can tell, this is not possible in the current implementation of scales as all of the given functions apply to both upper and lower limits. Is there currently a workaround for this or would it be possible to implement one?

**Comment by teunbrand** [comment]
In ggplot2, the `oob` argument to a scale can take arbitrary functions. I suggest that the current workaround is to use this feature with a function that does this asymmetric oob-handling.

``` r
library(ggplot2)

ggplot(faithful, aes(waiting, eruptions)) +
  geom_point() +
  scale_y_continuous(
    limits = c(2, 4),
    oob = function(x, range) {
      x[x < range[1]] <- NA
      pmin(x, range[2])
    }
  )
#> Warning: Removed 51 rows containing missing values (`geom_point()`).
```

![](https://i.imgur.com/QNVTjE3.png)

<sup>Created on 2022-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mdefende** [comment]
Ah that makes perfect sense! Thank you!
