### ISSUE TITLE
In label_date_short, can all days, months and years be lined up (regardless of the vjust selected)?

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/scales#352]
`scale_date_short` would look better if all the date labels of the same level lined up.

So in the example below, the "Oct" and "Apr" labels would be in line with the "Jan" and "Jul" labels
![image](https://user-images.githubusercontent.com/55065152/171774672-fd3e592b-275d-479e-beec-f952ede667af.png)

**Comment by teunbrand** [comment]
This seems like an issue with the `vjust` of the labels, which in ggplot2 you can change with `+ theme(axis.text.x.bottom = element_text(vjust = 1))`.

**Comment by davidhodge931** [comment]
You can make things better, but that excessively cramps things too close to the axis line and ticks. I think it would be much nicer, if the vjust applied to the line of the applicable level of label. Not with regard to all of the levels of labels

**Comment by davidhodge931** [comment]
Sometimes you get situations like this...

<img width="428" alt="image" src="https://user-images.githubusercontent.com/55065152/171986896-68c22122-0537-4b7b-af5e-3aff2a3f7d33.png">

This function would be much improved if all days were able to line-up, all months able to line -up, and all years able to line-up

**Comment by davidhodge931** [comment]
A way to do this would be to construct breaks so that empty lines are given "", such that all labels have some number of lines. 

In the example above:

* the label that is "16" above, would instead be a string "16\n \n " 
* the label above that is "06\nJune" would instead be "06\nJune\n"

etc.

**Comment by davidhodge931** [comment]
This seems to have somehow got fixed, even though no code has been added to main??

``` r
library(tidyverse)
economics |> 
  filter(between(date, ymd("1990-01-01"), ymd("1990-03-01"))) |> 
  ggplot() +
  geom_line(aes(date, unemploy)) +
  scale_x_date(labels = scales::label_date_short())
```

![](https://i.imgur.com/Xw2Y41Q.png)

<sup>Created on 2023-07-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by teunbrand** [comment]
Huh, interesting. I checked scales and stringi, but got no clue where this fix was applied :-)

**Comment by davidhodge931** [comment]
Pretty weird, but great :) Closed the PR as well

Maybe it was grid or vctrs, or something else..
