### ISSUE TITLE
Add `style_positive` and `style_negative` to other continuous labelers

### ISSUE THREAD

**Issue by bwiernik** [r-lib/scales#356]
I most often work with numbers that are changes in percentages (e.g., -2%, +5%). I mostly use `label_percent()` for this. However, I'd like to be able to use the `style_positive` and `style_negative` arguments from `label_number()` to format with proper plus and minus signs. Would it be possible to add these arguments to other continuous labelers (especially `label_percent()`)?

**Comment by factorialmap** [comment]
library(scales)

demo_continuous(c(-50,50),
                labels = label_percent(scale = 1,
                                       style_positive = "plus",
                                       style_negative = "minus")
                )


hope this help

**Comment by bwiernik** [comment]
Ah, so the issue is just that they aren't documented

**Comment by pearsonca** [comment]
@bwiernik i've proposed a revision that addresses this, by changing where `...` points to (namely, `label_numeric`, which includes the `style_(positive|negative)` documentation - is sufficient change?

**Comment by bwiernik** [comment]
That should work
