### ISSUE TITLE
Feature request: `label_number()` can prepend '≤' and '≥' symbols

### ISSUE THREAD

**Issue by teunbrand** [r-lib/scales#368]
When plotting a scale with squished oob-handling, I often find it clearer to indicate this with the ≤ and ≥ symbols prepended to the first and last labels respectively. Currently, this requires manually setting breaks and labels.

``` r
library(ggplot2)
library(scales)

ggplot(faithful, aes(waiting, eruptions)) +
  geom_point() +
  scale_y_continuous(
    limits = c(2, 4),
    breaks = c(2, 2.5, 3, 3.5, 4),
    labels = c("≤2.0", "2.5", "3.0", "3.5", "≥4.0"),
    oob = oob_squish
  )
```

![](https://i.imgur.com/WoRJhRX.png)

<sup>Created on 2022-11-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I think it would be great if this could be an option in the `label_number()` function, for example with a `squished` argument taking a logical vector for the lower and upper limit respectively.

``` r
ggplot(faithful, aes(waiting, eruptions)) +
  geom_point() +
  scale_y_continuous(
    limits = c(2, 4),
    labels = scales::label_number(squished = c(TRUE, TRUE)),
    oob = oob_squish
  )
```

**Comment by thomasp85** [comment]
I don't think this sort of special behaviour fits into scales. It is pretty easy to wrap `label_number()` in a function that prepends this to the output if you need it often

```r
ggplot(faithful, aes(waiting, eruptions)) +
    geom_point() +
    scale_y_continuous(
        limits = c(2, 4),
        labels = \(...) {l <- scales::label_number()(...); l[c(1, length(l))] <- paste0(c("≤","≥"), l[c(1, length(l))]); l},
        oob = oob_squish
    )
```
