### ISSUE TITLE
label_scientific digits

### ISSUE THREAD

**Issue by AndreeWarby** [r-lib/scales#378]
Hi there,

When trying to use label_scientific and specifying the number of digits using digits = 2, it will not apply to numbers that are only showing 1 digit before the exponent. I also noted that in the examples provided when digits=3 is used, also doesn't appear to change anything from the example that doesn't include the digits argument (https://scales.r-lib.org/reference/label_scientific.html).

demo_continuous(c(1, 10))
demo_continuous(c(1, 10), labels = label_scientific())
demo_continuous(c(1, 10), labels = label_scientific(digits = 3))

Is there something I am missing or is there an issue with the digits argument?

**Comment by thomasp85** [comment]
The `digits` argument works in the same way as in `base::format()`. It is a suggestion and a maximum number of digits. The output will not use more digits than necessary to differentiate between the output
