### ISSUE TITLE
`label_date_short()` doesn't uniquely identify centuries?

### ISSUE THREAD

**Issue by joshuaylevy** [r-lib/scales#384]
First-time issue submitter here...

I've been trying to pretty-up a figure for a presentation and was fiddling around with `label_date_short()`.
It handles other time POSIX values really well but can't get it to uniquely identify years and centuries.
For example: I have a dataset that spans centuries for which I'm trying to plot data and want to label the horizontal axis in 5-year increments but still save space. So, tick-marks would read: `1895, 1900, 05, 10 ... 95, 2000, 05, 10, 15`.

The code that I am using is as follows:
```r
scale_x_date(
        name = "Year",
        limits = c(
            as_date("1895", format = "%Y"),
            as_date("2015", format = "%Y")
        ),
        breaks = breaks_width("5 years"),
        labels = label_date_short(format = c("%y", "%C"))
    ) +
```

The above code produces the following horizontal axis:
![image](https://user-images.githubusercontent.com/90637467/232889300-70bf2d9e-5c5d-4871-a6dd-684e3c6551b0.png)

Reversing the arguments in the format vector (so that it reads `c("%C", "%y")` only prints out the leading two digits of the year (i.e `18, 19, 19, 19 ... 20`

This makes me think that the function `label_date_short()` doesn't handle centuries properly? Is that the case or am I missing something shockingly obvious?

Thanks so much for your help and contributions!

**Comment by thomasp85** [comment]
There is currently no facility to do what you are after I'm afraid
