### ISSUE TITLE
`*_trans` suffixed functions would be easier to use if they were renamed to be `trans_*` prefixed functions

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/scales#390]
A trans prefix would work well with the Rstudio auto-complete making it easier to search through the functions.

It would also be consistent with `scales::oob_*` functions, `ggplot2::stat_*` functions, and `ggplot2::position_*` functions etc.

**Comment by teunbrand** [comment]
Indirectly related to this, it would also be nice to have the palette functions have the `pal_*` prefix instead of suffix.
