### ISSUE TITLE
Rescale formula/calculation

### ISSUE THREAD

**Issue by Saadi4469** [r-lib/scales#395]
I would like to know the formula used in rescale. The purpose is to implement the same calculation in MS-Excel.

Thank you

**Comment by teunbrand** [comment]
``` r
print(scales:::rescale.numeric)
#> function (x, to = c(0, 1), from = range(x, na.rm = TRUE, finite = TRUE), 
#>     ...) 
#> {
#>     if (zero_range(from) || zero_range(to)) {
#>         return(ifelse(is.na(x), NA, mean(to)))
#>     }
#>     (x - from[1])/diff(from) * diff(to) + to[1]
#> }
#> <bytecode: 0x000002261aa1f620>
#> <environment: namespace:scales>
```

<sup>Created on 2023-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Or by default `from` argument:

$\frac{x - min(x)}{max(x) - min(x)} * (end - start) + start$

Where $end$ is `to[2]` and $start$ is `to[1]`. With default `to` argument, simplifies to:

$\frac{x - min(x)}{max(x) - min(x)}$

**Comment by Saadi4469** [comment]
Awesome, thank you for the quick response :)

**Comment by Saadi4469** [comment]
What is x in x - min(x)?

**Comment by thomasp85** [comment]
Closing this. The input arguments are well documented in the code and further questions should be asked at e.g. https://community.rstudio.com/ as the issue tracker is mainly to track bugs and feature requests
