### ISSUE TITLE
Feature request: palette registration

### ISSUE THREAD

**Issue by teunbrand** [r-lib/scales#396]
I think it would be great if there was some mechanism in which packages can register a colour palette that then could natively interface with scales/ggplot2. It would save having to write separate `scale_colour/fill_*()` functions for packages providing the palettes, and save having to write `scale_{custom_colour_aesthetic}_{palette_type}` for packages that extend layers with custom colour-like aesthetics.

From a palette package POV you might then call

```r
scales::register_palette(name = "foobar", type = "qualitative", fun = my_palette_fun)
```

This then gets stored in a list from which one could retrieve

```r
scales::pal_registered(type = "qualitative", name = "foobar")
```

Which then gets used in e.g. ggplot2 scales. A nicety that can be added is to pre-populate these list of registered palettes with R's build-in palettes.

**Comment by davidhodge931** [comment]
Awesome work - this will be super useful! I wonder if the `set_palette` function here could be called `register_palette` @teunbrand? This might reflect more accurately what it does. I.e. nothing is set for subsequent plots. It's just available to be retrieved. This stuff is subjective, so maybe what you've got is better. I just would expect setting a palette would change the colours by default

**Comment by teunbrand** [comment]
Hmm, I like set `set_/get_` symmetry, but I suppose it could be `set_registered_palette()` and `get_registered_palette()` to make it somewhat less ambiguous.

**Comment by davidhodge931** [comment]
Hmm, `set_registered_palette` does look a little long-winded.

Another idea: `set_known_palette` and `get_known_palette`?
