### ISSUE TITLE
Rescale with a vector of 0

### ISSUE THREAD

**Issue by BioinformaNicks** [r-lib/scales#401]
Hi,

Is it the intended behaviour that the rescale function does the following?
`rescale(c(0,0,0,0), to = c(0,100))`
[1] 50 50 50 50

Wouldn't it be more logical to still have a zero stay zero?

**Comment by teunbrand** [comment]
It seems very much by design that if `from` has no/zero range, the result has `mean(to)` as value.
``` r
scales:::rescale.numeric
#> function (x, to = c(0, 1), from = range(x, na.rm = TRUE, finite = TRUE), 
#>     ...) 
#> {
#>     if (zero_range(from) || zero_range(to)) {
#>         return(ifelse(is.na(x), NA, mean(to)))
#>     }
#>     (x - from[1])/diff(from) * diff(to) + to[1]
#> }
#> <bytecode: 0x000001d3024e1bc0>
#> <environment: namespace:scales>
```

<sup>Created on 2023-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
