### ISSUE TITLE
Feature request: `rescale.AsIs` method

### ISSUE THREAD

**Issue by teunbrand** [r-lib/scales#403]
In ggplot2 we're considering to let `AsIs` vectors be unresponsive to scales in https://github.com/tidyverse/ggplot2/pull/5477.
What would work really well for that PR, is if {scales} would define a `recale` method for `AsIs` objects that returns input unaltered.

My proposal is simply the following:

```
rescale.AsIs <- function(x, to, from, ...) {
  x
}
```

Currently, no such method exists, so we're unlikely to be harming any existing code out there:
``` r
scales::rescale(I(1:3))
#> Error in UseMethod("rescale"): no applicable method for 'rescale' applied to an object of class "AsIs"
```

<sup>Created on 2023-10-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by thomasp85** [comment]
Sounds good to me. Would you like to create a PR?

**Comment by teunbrand** [comment]
Yes, I'll prepare one later today.
