### ISSUE TITLE
scales: 2 issues

### ISSUE THREAD

**Issue by JJHelly** [r-lib/scales#412]
Aloha.
Just discovered scales and want to thank you for that.  I find a couple of things to comment on.

1. scale_x_continuous(labels = scales::label_number(accuracy = 0.5),
     	                  breaks = c(-124, -120, -116)) 
                  if accuracy = 0.0 (ie, integer) then the values on the axis are NA.

2. It seems to me that 'accuracy' is more correctly 'precision'

Mahalo for the work.

**Comment by teunbrand** [comment]
To round to integers you should use `accuracy = 1`, not `accuracy = 0`.
With regards to the accuracy/precision distinction, I don't really know what distinguishes these terms with regards to number formatting. However, I've seen 'precision' used to roughly mean 'the number of digits', which is not what the `accuracy` argument encodes.

**Comment by thomasp85** [comment]
`accuracy` is correctly used here as it relates to how accurate the resulting label is to the true value. `precision` is more related to sampling and how good you are at repeating a measurement
