### ISSUE TITLE
Feature request: Could `label_*` functions support labelling every nth break?

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/scales#436]
This is useful, as it provides another way to get the breaks & labels  you want - and it can work well depending on the theme used.

I think it'd be ideal if this could be expressed as an argument `every_nth` argument in each label_* function. 

This would then provide a way for the user to then determine the the frequency of labels (e.g. provide a label every 2nd break), and an offset (to start at not the first break if desired).

This is following on from this discussion here https://github.com/tidyverse/ggplot2/issues/5881

**Comment by davidhodge931** [comment]
An example of a situation where this is useful.. 

A plot of monthly cases, where you want to demonstrate that it is monthly on the x axis using monthly minor breaks. 

..But labelling every year does not fit for the size of image that you want to make. It works nice to label every 2nd break in this case

<img width="392" alt="image" src="https://github.com/user-attachments/assets/014d35a2-a4c3-46c6-b37f-5aaba4599eae">

**Comment by thomasp85** [comment]
I think the new `compose_label()` function is the way to go about this. Adding such functionality to every labelling function would be too big a change for what it provides.
