### ISSUE TITLE
Feature request: an option to remove leading zeros in `label_date_short()` 

### ISSUE THREAD

**Issue by lz1nwm** [r-lib/scales#442]
Is it possible to implement an option to remove leading zeros in `label_date_short()`?

![Untitled1](https://github.com/r-lib/scales/assets/10129222/f7f90882-d2f5-4e42-9090-2b0bfa099099)

**Comment by teunbrand** [comment]
The `format.Date()` via `strptime()` does not support no leading characters.
You can replace the zero with a space though:

``` r
x <- seq(Sys.Date(), Sys.Date() + 365, by = "1 month")
labels <- scales::label_date_short(format = c("%Y", "%b", "%e", "%H:%M"))
labels(x)
#>  [1] " 3\nOct\n2024" " 3\nNov"       " 3\nDec"       " 3\nJan\n2025"
#>  [5] " 3\nFeb"       " 3\nMar"       " 3\nApr"       " 3\nMay"      
#>  [9] " 3\nJun"       " 3\nJul"       " 3\nAug"       " 3\nSep"      
#> [13] " 3\nOct"
```

<sup>Created on 2024-10-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by lz1nwm** [comment]
Thanks, I know that but it doesn't look centered. I thought that it could be as simple as implementing something like:
```r
gsub("^0", "", format(as.Date("2024-09-02"), "%m\n%Y"))
```
...but maybe it's not
