### ISSUE TITLE
Feature request: Could `scales::number` etc have a `style_negative` option of `"none"`?

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/scales#443]
"none" is useful option for population pyramids, where you hack the data by multiplying the Female population 

This should also flow into all of the `label_*()` functions.

So the argument would look like...
```
number(
  ...,
  style_negative = c("hyphen", "minus", "parens", "none"),
```

and the help would have an extra bullet...

* "none" removes any negative styling. 

Could be something for Tidy Dev Day?

**Comment by davidsirl** [comment]
My experience is that this is possible with a slightly different approach to that suggested:
```
scale_x_continuous(breaks = pop_breaks, labels = abs(pop_breaks)),
```
where `pop_breaks` is organised beforehand as `values_plotted |> abs() |> max()` and then using `base::pretty()` to make the breakpoints nice round numbers.

(https://www.njtierney.com/post/2022/08/09/ggplot-pyramid/ was my source for that)

One can "tidy up" such labels further by using comma() but (i) comma() is superseded and (ii) I do not see how to do the same sort of thing with the superseding function label_comma().

**Comment by teunbrand** [comment]
I'm sorry David but I genuinely think this is not a good idea, but I get why it might be useful.
Overall, omitting a minus indication is misleading and we want to make it harder to put up misleading labels, not easier.
I get this then requires some extra effort to label pyramid plots, but this is a specialised plot and the creator should just take some care to `abs()` their values before labelling.

**Comment by davidhodge931** [comment]
Cool, thanks @teunbrand

**Comment by davidsirl** [comment]
I'm not sure I agree  @teunbrand. Any plot can easily be made misleading and, like most plot options, this sort of functionality would aid informative labelling in some situations too. But if that's the decision then fair enough and thank you for explaining it.
