### ISSUE TITLE
Missing bracket in `date_format()` documentation

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [r-lib/scales#451]
While reading the documentation for `date_format()` I noticed that there is a missing bracket causing the link to `label_date()` to be missing.

https://github.com/r-lib/scales/blob/6e5e4c352b36b0903ebcc484264e2e741cd93922/R/label-date.R#L154

should be
```
#' to [label_date()]/[label_time()] for new code. 
```

I am happy to open a PR for this if you would like but it is pretty trivial so you might want to just fix it yourself. Let me know.

**Comment by teunbrand** [comment]
A PR would be wonderful :)
