### ISSUE TITLE
Could `label_date_short` default to `leading = ""` 

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/scales#471]
Thanks for this new feature with the leading argument :)

I think 99% of the time, users would prefer to use `leading = ""` rather than `leading = ""`. It allows for shorter more readable labels which is in keeping with the name and intent of the function. 

So I was wondering if the default in `label_date_short` could be changed to `leading = ""`?

**Comment by thomasp85** [comment]
This would deviate from the previous default and thus break existing code. For this reason we want to keep it opt-in
