### ISSUE TITLE
should percent_format allow variable precision?

### ISSUE THREAD

**Issue by AndrewsOR** [r-lib/scales#76]
I've noticed that when using `percent(x)`, if elements of x are of of different orders of magnitude, percent will pick the precision that works for the largest element.  

```
> percent(c(0.123,0.000234))
[1] "12.3%" "0.0%" 
```

In other words, precision is constant -- the number of significant figures is not.  But sometimes when making a decision tree or a table for a report it's nice to have constant significant figures.

The [workaround ](http://stackoverflow.com/questions/34934374/percentage-with-significant-digits) I currently use is easy enough:

```
> sapply(c(0.123,0.000234), percent)
[1] "12.3%"  "0.0234%"
```

to ensure reverse compatibility, maybe something like

```
percent(x, adjust=FALSE)
```

where `adjust=TRUE` would ensure a consistent number of significant figures

**Comment by danwwilson** [comment]
Any chance of merging #77 into the master or addressing it by extending the code? It would be great to be able to change the `big,mark` and `decimal.mark` at the very least to assist with European representation of numbers.
