### ISSUE TITLE
breaks for log scales

### ISSUE THREAD

**Issue by kohske** [r-lib/scales#9]
```
> log_breaks(base = 10)(1:1000)
[1]    0  200  400  600  800 1000
> log_breaks(base = 2)(1:1000)
[1]   1   8  64 512
```

but I expect like this:

```
> 10^pretty(log10(1:1000), 5)
[1]    1.000000    3.162278   10.000000   31.622777  100.000000  316.227766 1000.000000
```

log10 with [1, 1000] makes break equally-spaced n original (untransformed) data, while log2 with [1, 1000] in transformed data.
This is because (log10(1000) - log10(1)) / n < 1, but in this case, the threshold is not appropriate.

I'm not sure when this change is useful.

see also this commit: 947f97ce1aef3233990d968b406348aa44763de2

**Comment by hadley** [comment]
Have you had any more thoughts on this?

**Comment by sjackman** [comment]
Somewhat related, I really like the "engineering" 1-2-5 log scale:
1 2 5 10 20 50 100 200 500 et cetera
See https://en.wikipedia.org/wiki/Preferred_number#1-2-5_series

**Comment by hadley** [comment]
@sjackman want to contribute a labeller???

**Comment by sjackman** [comment]
Yeah, actually, I would. The next time it comes up, I'll do that. Can you point me to a template of code that I can crib and modify?

**Comment by hadley** [comment]
@sjackman I'd start with the existing `log_breaks()`: https://github.com/hadley/scales/blob/master/R/breaks.r#L47

**Comment by cb4github** [comment]
Might this be what you had in mind:

```
log_breaks_fill <- function(fill = "full", ...) {
  function(x) {
    sparse <- log_breaks(...)(x)
    if (fill == "eng") {
      fillVec <- c(1,2,5)
    } else if (fill == "full") {
      fillVec <- 1:9
    } else if (fill == "none") {
      fillVec <- 1
    } else {
      warning(paste0("Unrecognized fill option ignored:", fill))
      fillVec <- 1
    }
    return(as.vector(fillVec %o% sparse))
  }
}
```

**Comment by sjackman** [comment]
I'll try that out. Thanks!

**Comment by sjackman** [comment]
@cb4github The following works very well. Thanks for the suggestion!

```r
library(scales)
library(tidyverse)
log_breaks_125 <- function(...) c(1, 2, 5) %o% log_breaks()(...)
ggplot(diamonds, aes(x = carat, y = price)) +
	scale_x_log10(breaks = log_breaks_125) +
	scale_y_log10(breaks = log_breaks_125) +
	geom_point()
```

![image](https://user-images.githubusercontent.com/291551/41796845-c4a6e78a-761c-11e8-8cff-b68250917da0.png)
