### ISSUE TITLE
`percent` gives NaN% for all values in column if any one is NaN

### ISSUE THREAD

**Issue by bradhannigandaley** [r-lib/scales#97]
Supposing I have a tibble with numeric columns `y` and `x` and I want to format `p = y/x` as a percentage, if there are any zero values of `x` then _all_ values of `p = percent(y/x)` are `NaN%` rather than only where `x==0`. I imagine this is a consequence of the logic that forces constant precision, as mentioned in #76 .

**Comment by chyx** [comment]
To be exact, this happens when any one of the value is Inf:

> library(scales)
> percent(Inf)
[1] "NaN%"
> percent(c(1, Inf))                                                                                                                                                                                                
[1] "NaN%" "NaN%"
> percent(c(1, NaN))                                                                                                                                                                                                
[1] "100%" "NaN%"
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

**Comment by dpseidel** [comment]
fixed by #142

**Comment by hadley** [comment]
I don't think we're using `number_format()` in `percent()` yet?

**Comment by dpseidel** [comment]
It's fixed in the precision function in #142.

**Comment by dpseidel** [comment]
`percent()` calls `precision()` which is where infinite values are now handled. I tested it to ensure it is indeed fixed, but perhaps this will change again in the next PR?  I don't expect it to break again though.

**Comment by hadley** [comment]
Oh, got it!
